# Generated by Django 5.0.2 on 2024-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gender_valid', models.BooleanField()),
                ('forms', models.ManyToManyField(to='core.formdetail', verbose_name='template')),
            ],
        ),
    ]
