# Generated by Django 5.0.2 on 2024-02-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplate',
            name='gender_valid',
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='age_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='disabilitiy_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='employment_status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='ethnicity_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='gender_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='pronouns_active',
            field=models.BooleanField(default=True),
        ),
    ]
