# Generated by Django 5.0.2 on 2024-02-28 20:47

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_formtemplate_gender_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplate',
            name='forms',
        ),
        migrations.AddField(
            model_name='formdetail',
            name='age',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='formdetail',
            name='disabilitiy',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='formdetail',
            name='employment_status',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='formdetail',
            name='ethnicity',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='formdetail',
            name='pronouns',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='formdetail',
            name='template',
            field=models.ForeignKey(default=core.models.FormTemplate.get_default_pk, on_delete=django.db.models.deletion.DO_NOTHING, to='core.formtemplate', verbose_name='forms'),
        ),
    ]
